import { defineView, ViewType } from 'twenty-sdk/define';

import {
  ALL_LEADS_TABLE_VIEW_UUID,
  LEAD_ASSIGNED_TEAM_FIELD_UUID,
  LEAD_ASSIGNED_TO_FIELD_UUID,
  LEAD_CALL_STATUS_FIELD_UUID,
  LEAD_CITY_FIELD_UUID,
  LEAD_CLINIC_NAME_FIELD_UUID,
  LEAD_CONVERSION_PROBABILITY_FIELD_UUID,
  LEAD_DOCTOR_NAME_FIELD_UUID,
  LEAD_EMAILS_FIELD_UUID,
  LEAD_EXPECTED_CLOSURE_DATE_FIELD_UUID,
  LEAD_INTEREST_LEVEL_FIELD_UUID,
  LEAD_NEXT_FOLLOW_UP_AT_FIELD_UUID,
  LEAD_OBJECT_UNIVERSAL_IDENTIFIER,
  LEAD_PHONES_FIELD_UUID,
  LEAD_PRIORITY_FIELD_UUID,
  LEAD_SOURCE_FIELD_UUID,
  LEAD_SPECIALIZATION_FIELD_UUID,
  LEAD_STAGE_FIELD_UUID,
  LEAD_STATE_FIELD_UUID,
} from 'src/constants/universal-identifiers';

export default defineView({
  universalIdentifier: ALL_LEADS_TABLE_VIEW_UUID,
  name: 'All Leads',
  objectUniversalIdentifier: LEAD_OBJECT_UNIVERSAL_IDENTIFIER,
  type: ViewType.TABLE,
  icon: 'IconList',
  position: 0,
  fields: [
    { universalIdentifier: '08315385-ecda-428c-bc2c-1d8d21cef90f', fieldMetadataUniversalIdentifier: LEAD_DOCTOR_NAME_FIELD_UUID, position: 0, isVisible: true },
    { universalIdentifier: '8409467b-2907-4f5e-b65d-671edb9937f5', fieldMetadataUniversalIdentifier: LEAD_CLINIC_NAME_FIELD_UUID, position: 1, isVisible: true },
    { universalIdentifier: 'd55360b3-dc8c-46fe-b5bf-f4db860d0139', fieldMetadataUniversalIdentifier: LEAD_STAGE_FIELD_UUID, position: 2, isVisible: true },
    { universalIdentifier: 'db653011-2b99-4e17-872e-1151e7758699', fieldMetadataUniversalIdentifier: LEAD_SPECIALIZATION_FIELD_UUID, position: 3, isVisible: true },
    { universalIdentifier: '3725b355-233e-444e-abb3-a10348d8d387', fieldMetadataUniversalIdentifier: LEAD_ASSIGNED_TO_FIELD_UUID, position: 4, isVisible: true },
    { universalIdentifier: '913874b6-d498-4478-9dd9-9f42a451c3e1', fieldMetadataUniversalIdentifier: LEAD_ASSIGNED_TEAM_FIELD_UUID, position: 5, isVisible: true },
    { universalIdentifier: 'edf60be9-f4a7-47f7-8bdf-530f2dc32fef', fieldMetadataUniversalIdentifier: LEAD_PHONES_FIELD_UUID, position: 6, isVisible: true },
    { universalIdentifier: 'bce33d22-b088-4a1c-b60d-ffadf343ab56', fieldMetadataUniversalIdentifier: LEAD_EMAILS_FIELD_UUID, position: 7, isVisible: true },
    { universalIdentifier: 'a962b30f-8287-4733-ade4-2e3dab690c1d', fieldMetadataUniversalIdentifier: LEAD_CITY_FIELD_UUID, position: 8, isVisible: true },
    { universalIdentifier: 'fd139a7d-56ac-421b-9f79-5647cfe4259e', fieldMetadataUniversalIdentifier: LEAD_STATE_FIELD_UUID, position: 9, isVisible: true },
    { universalIdentifier: '7b8ccedf-5a31-40d5-9fb8-44433db5ad27', fieldMetadataUniversalIdentifier: LEAD_PRIORITY_FIELD_UUID, position: 10, isVisible: true },
    { universalIdentifier: '7ed19a8b-5e16-4a06-9a77-fe8eafa73de9', fieldMetadataUniversalIdentifier: LEAD_INTEREST_LEVEL_FIELD_UUID, position: 11, isVisible: true },
    { universalIdentifier: '552c6122-9898-41c6-a4c5-cbc65a391f19', fieldMetadataUniversalIdentifier: LEAD_CALL_STATUS_FIELD_UUID, position: 12, isVisible: true },
    { universalIdentifier: '3aa4c8cc-6fee-41d5-8b3c-a3a2b6bf93e9', fieldMetadataUniversalIdentifier: LEAD_NEXT_FOLLOW_UP_AT_FIELD_UUID, position: 13, isVisible: true },
    { universalIdentifier: '5a6ede01-5ee7-4430-9203-d6bbbb36e3e7', fieldMetadataUniversalIdentifier: LEAD_CONVERSION_PROBABILITY_FIELD_UUID, position: 14, isVisible: false },
    { universalIdentifier: 'b7a2a1dc-e0f0-41a7-966b-5d156cec31c7', fieldMetadataUniversalIdentifier: LEAD_EXPECTED_CLOSURE_DATE_FIELD_UUID, position: 15, isVisible: false },
    { universalIdentifier: '12022bc8-0bd6-43e0-a81d-701b9690cd85', fieldMetadataUniversalIdentifier: LEAD_SOURCE_FIELD_UUID, position: 16, isVisible: false },
  ],
});
