import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  LEAD_AI_CONFIDENCE_FIELD_UUID,
  LEAD_AI_NEXT_ACTION_FIELD_UUID,
  LEAD_AI_SUMMARY_FIELD_UUID,
  LEAD_AI_TAGS_FIELD_UUID,
  LEAD_BUDGET_RANGE_FIELD_UUID,
  LEAD_CALL_OUTCOME_FIELD_UUID,
  LEAD_CALL_STATUS_FIELD_UUID,
  LEAD_CITY_FIELD_UUID,
  LEAD_CLINIC_NAME_FIELD_UUID,
  LEAD_CONVERSION_PROBABILITY_FIELD_UUID,
  LEAD_DATA_CONFIDENCE_SCORE_FIELD_UUID,
  LEAD_DOCTOR_NAME_FIELD_UUID,
  LEAD_EMAILS_FIELD_UUID,
  LEAD_ENRICHMENT_SOURCE_FIELD_UUID,
  LEAD_ENRICHMENT_STATUS_FIELD_UUID,
  LEAD_EXPECTED_CLOSURE_DATE_FIELD_UUID,
  LEAD_EXTERNAL_ID_FIELD_UUID,
  LEAD_FOLLOW_UP_NOTES_FIELD_UUID,
  LEAD_IMPORT_BATCH_ID_FIELD_UUID,
  LEAD_IMPORTED_AT_FIELD_UUID,
  LEAD_INSTAGRAM_FIELD_UUID,
  LEAD_INTEREST_LEVEL_FIELD_UUID,
  LEAD_ASSIGNED_TEAM_FIELD_UUID,
  LEAD_LAST_CALL_DATE_FIELD_UUID,
  LEAD_LAST_CONTACTED_AT_FIELD_UUID,
  LEAD_MEETING_DATE_FIELD_UUID,
  LEAD_MEETING_MODE_FIELD_UUID,
  LEAD_MEETING_OUTCOME_FIELD_UUID,
  LEAD_NEXT_CALL_DATE_FIELD_UUID,
  LEAD_NEXT_FOLLOW_UP_AT_FIELD_UUID,
  LEAD_OBJECT_UNIVERSAL_IDENTIFIER,
  LEAD_OBJECTIONS_FIELD_UUID,
  LEAD_PHONES_FIELD_UUID,
  LEAD_POSITION_FIELD_UUID,
  LEAD_PRIORITY_FIELD_UUID,
  LEAD_SCORE_BAND_FIELD_UUID,
  LEAD_SCORE_EXPLANATION_FIELD_UUID,
  LEAD_SCORE_FIELD_UUID,
  LEAD_SCRAPED_AT_FIELD_UUID,
  LEAD_SOURCE_FIELD_UUID,
  LEAD_SPECIALIZATION_FIELD_UUID,
  LEAD_STAGE_FIELD_UUID,
  LEAD_STATE_FIELD_UUID,
  LEAD_TOWN_FIELD_UUID,
  LEAD_WEBSITE_ADDRESS_FIELD_UUID,
  LEAD_WEBSITE_FIELD_UUID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: LEAD_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'lead',
  namePlural: 'leads',
  labelSingular: 'Lead',
  labelPlural: 'Leads',
  description: 'A doctor or clinic lead for IDDA Assurance outreach',
  icon: 'IconStethoscope',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: LEAD_DOCTOR_NAME_FIELD_UUID,
  fields: [
    // ── Primary identity ───────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_DOCTOR_NAME_FIELD_UUID,
      type: FieldType.FULL_NAME,
      name: 'doctorName',
      label: 'Doctor Name',
      icon: 'IconUser',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_CLINIC_NAME_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'clinicName',
      label: 'Clinic Name',
      icon: 'IconBuilding',
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_PHONES_FIELD_UUID,
      type: FieldType.PHONES,
      name: 'phones',
      label: 'Phones',
      icon: 'IconPhone',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_EMAILS_FIELD_UUID,
      type: FieldType.EMAILS,
      name: 'emails',
      label: 'Emails',
      icon: 'IconMail',
      isNullable: true,
    },

    // ── Location ───────────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_TOWN_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'town',
      label: 'Town',
      icon: 'IconBuildings',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_CITY_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'city',
      label: 'City',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_STATE_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'state',
      label: 'State',
      icon: 'IconMap',
      isNullable: true,
    },

    // ── Classification ─────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_SPECIALIZATION_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'specialization',
      label: 'Specialization',
      icon: 'IconHeartRateMonitor',
      isNullable: true,
      options: [
        { id: 'ff21338c-4013-4ddc-805a-a7f163a479f6', value: 'DENTIST', label: 'Dentist', position: 0, color: 'sky' },
        { id: 'f0cfeefa-a3c1-4f01-bebb-bfb4fe04f2c0', value: 'DERMATOLOGIST', label: 'Dermatologist', position: 1, color: 'pink' },
        { id: '905c99dd-40db-4a20-979d-d447aa8aa48f', value: 'GENERAL_PHYSICIAN', label: 'General Physician', position: 2, color: 'green' },
        { id: 'dcd8bf8c-ec6d-4d27-b7cc-2e380f3701b8', value: 'PEDIATRICIAN', label: 'Pediatrician', position: 3, color: 'turquoise' },
        { id: '31469d9c-e37a-4c9a-915b-aaf4cef5c2b3', value: 'ENT', label: 'ENT', position: 4, color: 'blue' },
        { id: '64b9f29b-63d7-4504-9cfc-1a47e8b4ee7e', value: 'OPHTHALMOLOGIST', label: 'Ophthalmologist', position: 5, color: 'purple' },
        { id: 'd578b52a-a6e3-4f2d-99ba-2e58269626ff', value: 'GYNECOLOGIST', label: 'Gynecologist', position: 6, color: 'orange' },
        { id: '4167a404-aacf-43a8-8fdb-dcce532b10c9', value: 'ORTHOPEDIC', label: 'Orthopedic', position: 7, color: 'yellow' },
        { id: 'aece57b3-209a-46c8-b75c-f9b718a276d2', value: 'OTHER', label: 'Other', position: 8, color: 'gray' },
      ],
    },
    {
      universalIdentifier: LEAD_SOURCE_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'leadSource',
      label: 'Lead Source',
      icon: 'IconSourceCode',
      isNullable: true,
      options: [
        { id: '55943ef0-b75f-42f9-8801-0e80276f0c28', value: 'COLD_CALL', label: 'Cold Call', position: 0, color: 'sky' },
        { id: '301fc87d-2fa2-4da6-a180-d275f82c1344', value: 'REFERRAL', label: 'Referral', position: 1, color: 'green' },
        { id: '0dface1a-9ade-4483-8179-5f9f44b12ba4', value: 'INSTAGRAM', label: 'Instagram', position: 2, color: 'pink' },
        { id: '4debf90b-f13a-4149-bd72-d57974f55976', value: 'WEBSITE', label: 'Website', position: 3, color: 'blue' },
        { id: '30edfa37-4ec9-47b9-aa45-251a734c2a13', value: 'WALK_IN', label: 'Walk-in', position: 4, color: 'yellow' },
        { id: '4f80e384-0a9e-484f-bf5d-99e0a12952a7', value: 'LINKEDIN', label: 'LinkedIn', position: 5, color: 'purple' },
        { id: 'afc563e9-82b6-40f5-a5fe-58347563087b', value: 'EXHIBITION', label: 'Exhibition', position: 6, color: 'orange' },
        { id: '5c6b16a9-961d-40d2-9e69-174ae767d3a3', value: 'PARTNER', label: 'Partner', position: 7, color: 'turquoise' },
        { id: '0e7ba28a-95b5-40c0-b12a-35fafbab436c', value: 'SCRAPER', label: 'Scraper / Import', position: 8, color: 'gray' },
      ],
    },

    // ── Pipeline stage & priority ───────────────────────────────────────────
    {
      universalIdentifier: LEAD_STAGE_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'stage',
      label: 'Stage',
      icon: 'IconProgressCheck',
      defaultValue: "'NEW_LEAD'",
      options: [
        { id: '67ebc0d9-e0c7-46ea-b273-dddd7c6b84f5', value: 'NEW_LEAD', label: 'New Lead', position: 0, color: 'gray' },
        { id: 'f41b95d7-cda2-4ae6-bc95-eee5dd0527bc', value: 'RESEARCH_COMPLETED', label: 'Research Completed', position: 1, color: 'blue' },
        { id: 'c3c0c5f3-764c-4c5d-bd94-56019c7aff2c', value: 'READY_FOR_CALLING', label: 'Ready for Calling', position: 2, color: 'turquoise' },
        // UUID preserved from CONTACTED — value renamed to CONTACT_ATTEMPTED
        { id: '23dc6d51-d565-4a5d-81d9-630a98d6b947', value: 'CONTACT_ATTEMPTED', label: 'Contact Attempted', position: 3, color: 'sky' },
        { id: '862d38fe-1095-404a-98c5-23e9c6e24f34', value: 'FOLLOW_UP_PENDING', label: 'Follow-Up Pending', position: 4, color: 'yellow' },
        { id: '71cd5788-ce83-4db1-9083-4805da76ddc5', value: 'INTERESTED', label: 'Interested', position: 5, color: 'orange' },
        { id: 'a6d1f9a5-50fc-4650-bbe2-0e3e4d95bcfd', value: 'MEETING_SCHEDULED', label: 'Meeting Scheduled', position: 6, color: 'purple' },
        { id: '146c90a6-eb65-48c3-b38c-90d4556bafcd', value: 'MEETING_COMPLETED', label: 'Meeting Completed', position: 7, color: 'pink' },
        { id: '28a1e94e-38e9-4f3e-a580-d82e82b453af', value: 'NEGOTIATION', label: 'Negotiation', position: 8, color: 'green' },
        { id: 'a4837b25-a278-4084-83ff-b73d63fb7bd1', value: 'ONBOARDED', label: 'Onboarded', position: 9, color: 'green' },
        { id: 'dffb0d2c-e9c8-4d42-94f0-f8950aa1bb79', value: 'REJECTED', label: 'Rejected', position: 10, color: 'red' },
      ],
    },
    {
      universalIdentifier: LEAD_PRIORITY_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'priority',
      label: 'Priority',
      icon: 'IconFlag',
      defaultValue: "'MEDIUM'",
      options: [
        { id: '776118a4-60aa-4096-a0b1-4b092148c000', value: 'LOW', label: 'Low', position: 0, color: 'gray' },
        { id: '42daa674-f422-4c4f-930d-9eaea37c66c2', value: 'MEDIUM', label: 'Medium', position: 1, color: 'sky' },
        { id: '82f17979-d500-4c95-ab1a-266f98df31aa', value: 'HIGH', label: 'High', position: 2, color: 'orange' },
        { id: 'b3bee391-589c-4136-9a58-2c17f4fff264', value: 'URGENT', label: 'Urgent', position: 3, color: 'red' },
      ],
    },

    // ── Team ownership ─────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_ASSIGNED_TEAM_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'assignedTeam',
      label: 'Assigned Team',
      icon: 'IconUsersGroup',
      isNullable: true,
      options: [
        { id: 'b1a2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6', value: 'RESEARCH', label: 'Research Team', position: 0, color: 'blue' },
        { id: '2f5f4ea0-ad5c-4175-b3a6-a0fcd1a09e95', value: 'CALLING', label: 'Calling Team', position: 1, color: 'sky' },
        { id: '62589b2a-82b5-4afe-86cb-881fa4db191b', value: 'SALES', label: 'Sales Team', position: 2, color: 'green' },
        { id: 'c0f59fc0-b209-4999-b9df-cbafb6994f74', value: 'MANAGEMENT', label: 'Management', position: 3, color: 'purple' },
      ],
    },

    // ── Interest & sales scoring ────────────────────────────────────────────
    {
      universalIdentifier: LEAD_INTEREST_LEVEL_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'interestLevel',
      label: 'Interest Level',
      icon: 'IconThermometer',
      isNullable: true,
      options: [
        { id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', value: 'HOT', label: 'Hot', position: 0, color: 'red' },
        { id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901', value: 'WARM', label: 'Warm', position: 1, color: 'orange' },
        { id: 'be6c9b81-4a83-459f-bb5a-9b63771ebfd8', value: 'COLD', label: 'Cold', position: 2, color: 'sky' },
        { id: '31ce1d9a-16fb-44d0-aba9-aa496194ca88', value: 'NOT_INTERESTED', label: 'Not Interested', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: LEAD_CONVERSION_PROBABILITY_FIELD_UUID,
      type: FieldType.NUMBER,
      name: 'conversionProbability',
      label: 'Conversion %',
      icon: 'IconPercentage',
      isNullable: true,
      universalSettings: { decimals: 0, type: 'percentage' },
    },
    {
      universalIdentifier: LEAD_BUDGET_RANGE_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'budgetRange',
      label: 'Budget Range',
      icon: 'IconCurrencyRupee',
      isNullable: true,
      options: [
        { id: '43195e3d-b485-47ae-8472-a46c47d44185', value: 'BELOW_5K', label: 'Below Rs 5k/month', position: 0, color: 'gray' },
        { id: 'a5c1062e-8e6d-4962-8b2d-08c4a48f0946', value: 'RANGE_5K_10K', label: 'Rs 5k-10k/month', position: 1, color: 'blue' },
        { id: '7d422bcc-f5b8-4955-be6d-1c9cfcf32d91', value: 'RANGE_10K_25K', label: 'Rs 10k-25k/month', position: 2, color: 'sky' },
        { id: 'f21cadb9-4bc2-4aea-91d0-c29fb9322fed', value: 'RANGE_25K_50K', label: 'Rs 25k-50k/month', position: 3, color: 'green' },
        { id: 'f7059fa8-3c86-48ba-8393-44332595c222', value: 'ABOVE_50K', label: 'Above Rs 50k/month', position: 4, color: 'orange' },
      ],
    },
    {
      universalIdentifier: LEAD_EXPECTED_CLOSURE_DATE_FIELD_UUID,
      type: FieldType.DATE,
      name: 'expectedClosureDate',
      label: 'Expected Closure Date',
      icon: 'IconCalendarCheck2',
      isNullable: true,
    },

    // ── Call operations ────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_CALL_STATUS_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'callStatus',
      label: 'Call Status',
      icon: 'IconPhone',
      isNullable: true,
      options: [
        { id: 'bee55006-a805-4aad-9bc2-d540c96ec800', value: 'NOT_CALLED', label: 'Not Called', position: 0, color: 'gray' },
        { id: 'eae1d158-b6f5-4bcd-a61a-e90b9a0bd8dd', value: 'CALLED', label: 'Called', position: 1, color: 'blue' },
        { id: '0b88b9e5-1b66-431d-bae9-ff0741cda4e2', value: 'NO_ANSWER', label: 'No Answer', position: 2, color: 'yellow' },
        { id: '1aff0bf6-5a81-4ce9-88c3-5f68808312ad', value: 'CALL_BACK', label: 'Call Back Requested', position: 3, color: 'orange' },
        { id: '268c8843-5a59-43b9-aa15-e0df114976f8', value: 'BUSY', label: 'Busy / Not Reachable', position: 4, color: 'red' },
        { id: 'c1d2e3f4-a5b6-7890-8901-345678901234', value: 'WRONG_NUMBER', label: 'Wrong Number', position: 5, color: 'pink' },
      ],
    },
    {
      universalIdentifier: LEAD_CALL_OUTCOME_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'callOutcome',
      label: 'Call Outcome',
      icon: 'IconPhoneCheck',
      isNullable: true,
      options: [
        { id: 'd2e3f4a5-b6c7-8901-9012-456789012345', value: 'POSITIVE', label: 'Positive - Will Proceed', position: 0, color: 'green' },
        { id: '4bbede4b-1bb4-4b38-832a-8ca476fbab8d', value: 'NEUTRAL', label: 'Neutral - Needs More Info', position: 1, color: 'sky' },
        { id: '8e7f9e81-c11a-41e9-8764-ee74b23d621e', value: 'FOLLOW_UP', label: 'Follow-Up Needed', position: 2, color: 'yellow' },
        { id: '95c88660-7365-4de8-869c-7dd585663731', value: 'NOT_INTERESTED', label: 'Not Interested', position: 3, color: 'red' },
        { id: '7b226a10-5638-458d-8af2-c388e78e6f34', value: 'VOICEMAIL', label: 'Voicemail Left', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: LEAD_LAST_CALL_DATE_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'lastCallDate',
      label: 'Last Call Date',
      icon: 'IconPhoneIncoming',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_NEXT_CALL_DATE_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'nextCallDate',
      label: 'Next Call Date',
      icon: 'IconPhoneOutgoing',
      isNullable: true,
    },

    // ── Meeting operations ─────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_MEETING_DATE_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'meetingDate',
      label: 'Meeting Date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_MEETING_MODE_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'meetingMode',
      label: 'Meeting Mode',
      icon: 'IconVideo',
      isNullable: true,
      options: [
        { id: '4b56c579-77f8-4c62-9422-60d7a60e2376', value: 'IN_PERSON', label: 'In Person', position: 0, color: 'green' },
        { id: '39033189-98be-4bee-a2f9-8fcd16d905ac', value: 'VIDEO_CALL', label: 'Video Call', position: 1, color: 'blue' },
        { id: 'ffd5ded7-eff4-4c57-a022-5af27888fe74', value: 'PHONE_CALL', label: 'Phone Call', position: 2, color: 'sky' },
        { id: 'c80ae27f-03eb-4eee-a209-2b2dcf18bb43', value: 'WHATSAPP', label: 'WhatsApp', position: 3, color: 'turquoise' },
      ],
    },
    {
      universalIdentifier: LEAD_MEETING_OUTCOME_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'meetingOutcome',
      label: 'Meeting Outcome',
      icon: 'IconChecklist',
      isNullable: true,
      options: [
        { id: 'a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890', value: 'DEMO_GIVEN', label: 'Demo Given', position: 0, color: 'blue' },
        { id: 'b2c3d4e5-f6a7-8901-b2c3-d4e5f6a78901', value: 'PROPOSAL_SENT', label: 'Proposal Sent', position: 1, color: 'sky' },
        { id: '0cd89b85-fb40-4573-bdff-8337031681af', value: 'NEGOTIATING', label: 'Negotiating Terms', position: 2, color: 'yellow' },
        { id: 'e1ca1a9c-9efc-4095-a808-b16e79e182c7', value: 'CLOSED_WON', label: 'Closed - Won', position: 3, color: 'green' },
        { id: '70a48df8-4838-4054-9c29-2254f7226865', value: 'CLOSED_LOST', label: 'Closed - Lost', position: 4, color: 'red' },
        { id: 'd5d4e8b0-859c-4b28-b5c6-fb9fc207f029', value: 'RESCHEDULED', label: 'Rescheduled', position: 5, color: 'orange' },
      ],
    },

    // ── Notes & context ────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_FOLLOW_UP_NOTES_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'followUpNotes',
      label: 'Follow-Up Notes',
      icon: 'IconNotes',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_OBJECTIONS_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'objections',
      label: 'Objections',
      icon: 'IconAlertTriangle',
      isNullable: true,
      defaultValue: "''",
    },

    // ── Follow-up scheduling ───────────────────────────────────────────────
    {
      universalIdentifier: LEAD_LAST_CONTACTED_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'lastContactedAt',
      label: 'Last Contacted',
      icon: 'IconCalendarCheck',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_NEXT_FOLLOW_UP_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'nextFollowUpAt',
      label: 'Next Follow-Up',
      icon: 'IconCalendarClock',
      isNullable: true,
    },

    // ── Online presence ────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_WEBSITE_ADDRESS_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'websiteAddress',
      label: 'Website Address',
      icon: 'IconWorld',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_WEBSITE_FIELD_UUID,
      type: FieldType.LINKS,
      name: 'website',
      label: 'Website',
      icon: 'IconLink',
      isNullable: true,
    },
    {
      universalIdentifier: LEAD_INSTAGRAM_FIELD_UUID,
      type: FieldType.LINKS,
      name: 'instagram',
      label: 'Instagram',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },

    // ── Research ingestion metadata ─────────────────────────────────────────
    {
      universalIdentifier: LEAD_IMPORT_BATCH_ID_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'importBatchId',
      label: 'Import Batch ID',
      icon: 'IconPackageImport',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_ENRICHMENT_SOURCE_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'enrichmentSource',
      label: 'Enrichment Source',
      icon: 'IconDatabaseImport',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_DATA_CONFIDENCE_SCORE_FIELD_UUID,
      type: FieldType.NUMBER,
      name: 'dataConfidenceScore',
      label: 'Data Confidence %',
      icon: 'IconShieldCheck',
      isNullable: true,
      universalSettings: { decimals: 0, type: 'percentage' },
    },
    {
      universalIdentifier: LEAD_SCRAPED_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'scrapedAt',
      label: 'Scraped At',
      icon: 'IconRobot',
      isNullable: true,
    },

    {
      universalIdentifier: LEAD_EXTERNAL_ID_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'externalId',
      label: 'External ID',
      icon: 'IconFingerprint',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_ENRICHMENT_STATUS_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'enrichmentStatus',
      label: 'Enrichment Status',
      icon: 'IconSparkles',
      isNullable: true,
      options: [
        { id: 'e7b230f0-ffde-447d-8516-f9f79bff01f3', value: 'PENDING', label: 'Pending', position: 0, color: 'yellow' },
        { id: '2e1fb0c7-a0ff-46b7-b1b9-196ee5a315c2', value: 'ENRICHED', label: 'Enriched', position: 1, color: 'green' },
        { id: '53d71be0-996b-4c6a-b0b2-f9366e1cf9f0', value: 'MANUALLY_VERIFIED', label: 'Manually Verified', position: 2, color: 'blue' },
        { id: '1ab895e3-98e5-4547-86aa-f08f200f44a2', value: 'FAILED', label: 'Failed', position: 3, color: 'red' },
        { id: '4418fada-1b09-4eb0-9016-3102b45757f5', value: 'SKIPPED', label: 'Skipped', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: LEAD_IMPORTED_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'importedAt',
      label: 'Imported At',
      icon: 'IconDownload',
      isNullable: true,
    },

    // ── Lead Scoring (Phase 9) ─────────────────────────────────────────────
    {
      universalIdentifier: LEAD_SCORE_FIELD_UUID,
      type: FieldType.NUMBER,
      name: 'leadScore',
      label: 'Lead Score',
      icon: 'IconStar',
      isNullable: true,
      universalSettings: { decimals: 0 },
    },
    {
      universalIdentifier: LEAD_SCORE_BAND_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'scoreBand',
      label: 'Score Band',
      icon: 'IconTrendingUp',
      isNullable: true,
      options: [
        { id: '8687b82e-a043-44bc-96d6-f688a3f291c0', value: 'HOT', label: 'Hot', position: 0, color: 'red' },
        { id: '96102a7f-8b85-4730-9d7a-65f8e7087c7e', value: 'WARM', label: 'Warm', position: 1, color: 'orange' },
        { id: 'a68491c0-247f-4a52-95e0-c3f42dd64fe5', value: 'COLD', label: 'Cold', position: 2, color: 'sky' },
      ],
    },
    {
      universalIdentifier: LEAD_SCORE_EXPLANATION_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'scoreExplanation',
      label: 'Score Breakdown',
      icon: 'IconInfoCircle',
      isNullable: true,
      defaultValue: "''",
    },

    // ── AI Intelligence (Phase 12) ─────────────────────────────────────────
    {
      universalIdentifier: LEAD_AI_SUMMARY_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'aiLeadSummary',
      label: 'AI Summary',
      icon: 'IconBrain',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_AI_NEXT_ACTION_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'aiNextAction',
      label: 'AI Next Action',
      icon: 'IconBulb',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_AI_CONFIDENCE_FIELD_UUID,
      type: FieldType.NUMBER,
      name: 'aiConfidence',
      label: 'AI Confidence',
      icon: 'IconShieldHalf',
      isNullable: true,
      universalSettings: { decimals: 0, type: 'percentage' },
    },
    {
      universalIdentifier: LEAD_AI_TAGS_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'aiTags',
      label: 'AI Tags',
      icon: 'IconTags',
      isNullable: true,
      defaultValue: "''",
    },

    // ── System ────────────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_POSITION_FIELD_UUID,
      type: FieldType.POSITION,
      name: 'position',
      label: 'Position',
      icon: 'IconList',
      isNullable: true,
    },
  ],
});
