import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  LEAD_ACTIVITY_AI_SUMMARY_FIELD_UUID,
  LEAD_ACTIVITY_ATTACHMENT_URLS_FIELD_UUID,
  LEAD_ACTIVITY_COMM_CHANNEL_FIELD_UUID,
  LEAD_ACTIVITY_DESCRIPTION_FIELD_UUID,
  LEAD_ACTIVITY_DIRECTION_FIELD_UUID,
  LEAD_ACTIVITY_DURATION_FIELD_UUID,
  LEAD_ACTIVITY_EVENT_TYPE_FIELD_UUID,
  LEAD_ACTIVITY_FROM_VALUE_FIELD_UUID,
  LEAD_ACTIVITY_OBJECT_UUID,
  LEAD_ACTIVITY_OCCURRED_AT_FIELD_UUID,
  LEAD_ACTIVITY_POSITION_FIELD_UUID,
  LEAD_ACTIVITY_SENTIMENT_FIELD_UUID,
  LEAD_ACTIVITY_TO_VALUE_FIELD_UUID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: LEAD_ACTIVITY_OBJECT_UUID,
  nameSingular: 'leadActivity',
  namePlural: 'leadActivities',
  labelSingular: 'Lead Activity',
  labelPlural: 'Lead Activities',
  description: 'Immutable audit log and communication timeline entry for a lead',
  icon: 'IconActivity',
  isSearchable: false,
  labelIdentifierFieldMetadataUniversalIdentifier: LEAD_ACTIVITY_DESCRIPTION_FIELD_UUID,
  fields: [
    {
      universalIdentifier: LEAD_ACTIVITY_EVENT_TYPE_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'eventType',
      label: 'Event Type',
      icon: 'IconTag',
      options: [
        { id: 'bf0c7b03-3f13-41b1-88c0-ef647f4569b4', value: 'LEAD_CREATED', label: 'Lead Created', position: 0, color: 'blue' },
        { id: 'c4f651dd-8e1f-496e-9c98-c290db3e93c8', value: 'STAGE_CHANGED', label: 'Stage Changed', position: 1, color: 'purple' },
        { id: 'ff6ecfa7-1149-4bd5-b7df-5d7b021a8e8e', value: 'ASSIGNED_TO_CHANGED', label: 'Assigned To Changed', position: 2, color: 'sky' },
        { id: 'c633c71a-0ada-4229-88b9-052c91da7502', value: 'TEAM_CHANGED', label: 'Team Changed', position: 3, color: 'turquoise' },
        { id: 'b48a5350-8604-4343-a005-7d837a7113b9', value: 'CALL_ATTEMPTED', label: 'Call Attempted', position: 4, color: 'yellow' },
        { id: '6a833d2e-86b1-4aa8-bae1-7072adf0f1d0', value: 'CALL_OUTCOME_UPDATED', label: 'Call Outcome Updated', position: 5, color: 'orange' },
        { id: 'd50166c8-c215-4134-8ed9-90381d714070', value: 'MEETING_SCHEDULED', label: 'Meeting Scheduled', position: 6, color: 'green' },
        { id: '6d614ace-2523-496e-81ba-019733c8940d', value: 'MEETING_COMPLETED', label: 'Meeting Completed', position: 7, color: 'green' },
        { id: '645672d2-e75e-49f0-ba58-76948fc9973f', value: 'PRIORITY_CHANGED', label: 'Priority Changed', position: 8, color: 'pink' },
        { id: '2631aec3-0a1c-4f8a-b174-97dd434b9e99', value: 'INTEREST_LEVEL_UPDATED', label: 'Interest Level Updated', position: 9, color: 'red' },
        { id: 'f0bce2b4-2b2a-4fc4-80f8-504cda29e3d4', value: 'NOTE_ADDED', label: 'Note Added', position: 10, color: 'gray' },
        { id: '07492ba7-11a4-49ca-8e7f-61a747efde01', value: 'FOLLOW_UP_SCHEDULED', label: 'Follow-Up Scheduled', position: 11, color: 'yellow' },
        { id: 'c37eb747-9f7c-4879-840a-40f21efe9ca6', value: 'TASK_CREATED', label: 'Task Created', position: 12, color: 'blue' },
        { id: '647a6278-ca2b-46ad-bfd9-a8c07f2514c9', value: 'SCORE_UPDATED', label: 'Score Updated', position: 13, color: 'purple' },
        { id: '2f3271f6-714e-449c-87af-d37845f07752', value: 'CALL_MISSED', label: 'Call Missed / No Answer', position: 14, color: 'red' },
      ],
      defaultValue: "'LEAD_CREATED'",
    },
    {
      universalIdentifier: LEAD_ACTIVITY_FROM_VALUE_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'fromValue',
      label: 'Previous Value',
      icon: 'IconArrowLeft',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_ACTIVITY_TO_VALUE_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'toValue',
      label: 'New Value',
      icon: 'IconArrowRight',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_ACTIVITY_DESCRIPTION_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      icon: 'IconFileText',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_ACTIVITY_OCCURRED_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'occurredAt',
      label: 'Occurred At',
      icon: 'IconClock',
      isNullable: true,
    },

    // ── Communication Timeline (Phase 10) ──────────────────────────────────
    {
      universalIdentifier: LEAD_ACTIVITY_COMM_CHANNEL_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'communicationChannel',
      label: 'Channel',
      icon: 'IconMessageCircle',
      isNullable: true,
      options: [
        { id: 'aff4d22b-0aae-4572-b5e9-4be2b23e3e9d', value: 'CALL', label: 'Phone Call', position: 0, color: 'green' },
        { id: '8ff9ae43-e553-4fd8-b7bd-eafcd22fbec5', value: 'WHATSAPP', label: 'WhatsApp', position: 1, color: 'turquoise' },
        { id: 'd5b38f45-331b-46f8-ae07-ce4647ec8d29', value: 'EMAIL', label: 'Email', position: 2, color: 'blue' },
        { id: '2fd389b2-9381-4e20-8327-a3109c994782', value: 'MEETING', label: 'Meeting', position: 3, color: 'purple' },
        { id: 'f62c04e6-0403-4a9b-9a40-2128c6cabf30', value: 'NOTE', label: 'Manual Note', position: 4, color: 'gray' },
        { id: 'e633dc64-2bd2-42b9-b81d-e3c65d9eef11', value: 'SYSTEM', label: 'System Event', position: 5, color: 'sky' },
      ],
    },
    {
      universalIdentifier: LEAD_ACTIVITY_DIRECTION_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'direction',
      label: 'Direction',
      icon: 'IconArrowsExchange',
      isNullable: true,
      options: [
        { id: '28f0b5cb-59ae-4338-b6af-280f028acf9a', value: 'INCOMING', label: 'Incoming', position: 0, color: 'green' },
        { id: '2d71000f-26e3-4770-8ee7-46511a5b15c2', value: 'OUTGOING', label: 'Outgoing', position: 1, color: 'blue' },
        { id: '3623ad02-14cc-48fe-b10f-5d82383275ed', value: 'INTERNAL', label: 'Internal', position: 2, color: 'gray' },
      ],
    },
    {
      universalIdentifier: LEAD_ACTIVITY_DURATION_FIELD_UUID,
      type: FieldType.NUMBER,
      name: 'durationSeconds',
      label: 'Duration (sec)',
      icon: 'IconClockHour4',
      isNullable: true,
      universalSettings: { decimals: 0 },
    },
    {
      universalIdentifier: LEAD_ACTIVITY_ATTACHMENT_URLS_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'attachmentUrls',
      label: 'Attachments',
      icon: 'IconPaperclip',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: LEAD_ACTIVITY_SENTIMENT_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'sentiment',
      label: 'Sentiment',
      icon: 'IconMoodSmile',
      isNullable: true,
      options: [
        { id: '432ea6e9-71ec-467c-ad32-238a7bdccc18', value: 'POSITIVE', label: 'Positive', position: 0, color: 'green' },
        { id: 'dcb2ad48-40bd-4e2e-a7fd-ba6a0d665f0f', value: 'NEUTRAL', label: 'Neutral', position: 1, color: 'gray' },
        { id: '1b297280-97d1-456b-8718-352c8fd07658', value: 'NEGATIVE', label: 'Negative', position: 2, color: 'red' },
      ],
    },
    {
      universalIdentifier: LEAD_ACTIVITY_AI_SUMMARY_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'aiSummary',
      label: 'AI Summary',
      icon: 'IconBrain',
      isNullable: true,
      defaultValue: "''",
    },

    // ── System ────────────────────────────────────────────────────────────
    {
      universalIdentifier: LEAD_ACTIVITY_POSITION_FIELD_UUID,
      type: FieldType.POSITION,
      name: 'position',
      label: 'Position',
      icon: 'IconList',
      isNullable: true,
    },
  ],
});
