import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  TASK_COMPLETED_AT_FIELD_UUID,
  TASK_DESCRIPTION_FIELD_UUID,
  TASK_DUE_DATE_FIELD_UUID,
  TASK_OBJECT_UUID,
  TASK_POSITION_FIELD_UUID,
  TASK_PRIORITY_FIELD_UUID,
  TASK_REMINDER_AT_FIELD_UUID,
  TASK_STATUS_FIELD_UUID,
  TASK_TITLE_FIELD_UUID,
  TASK_TYPE_FIELD_UUID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: TASK_OBJECT_UUID,
  nameSingular: 'crmTask',
  namePlural: 'crmTasks',
  labelSingular: 'Task',
  labelPlural: 'Tasks',
  description: 'CRM task assigned to a team member, linked to a lead',
  icon: 'IconCheckbox',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: TASK_TITLE_FIELD_UUID,
  fields: [
    {
      universalIdentifier: TASK_TITLE_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'title',
      label: 'Title',
      icon: 'IconSubtask',
      defaultValue: "''",
    },
    {
      universalIdentifier: TASK_DESCRIPTION_FIELD_UUID,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      icon: 'IconFileText',
      isNullable: true,
      defaultValue: "''",
    },
    {
      universalIdentifier: TASK_TYPE_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'taskType',
      label: 'Task Type',
      icon: 'IconCategory',
      defaultValue: "'MANUAL'",
      options: [
        { id: 'f7bd11a8-04ff-4fbb-ad50-4c4c27c97ea7', value: 'FOLLOW_UP_CALL', label: 'Follow-Up Call', position: 0, color: 'green' },
        { id: '69ff5c59-c6a5-4570-be74-ddc3b6233aba', value: 'SEND_WHATSAPP', label: 'Send WhatsApp', position: 1, color: 'turquoise' },
        { id: '1ae34b3e-6235-4b1a-9789-4f3e3f642156', value: 'EMAIL', label: 'Send Email', position: 2, color: 'blue' },
        { id: '325c4094-ae67-4094-a271-2ad3944e4f58', value: 'MEETING', label: 'Meeting', position: 3, color: 'purple' },
        { id: '51a7d29a-8bae-487b-be37-bc6a2a61e035', value: 'RESEARCH', label: 'Research', position: 4, color: 'sky' },
        { id: '233b050e-7108-46a4-afa5-e2cae1e69ea6', value: 'MANUAL', label: 'Manual', position: 5, color: 'gray' },
      ],
    },
    {
      universalIdentifier: TASK_STATUS_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgressCheck',
      defaultValue: "'TODO'",
      options: [
        { id: 'aa8b0e6d-94f8-4086-923b-cd2d56d64529', value: 'TODO', label: 'To Do', position: 0, color: 'gray' },
        { id: '97247d38-9981-4a44-96f8-327226da2f1c', value: 'IN_PROGRESS', label: 'In Progress', position: 1, color: 'blue' },
        { id: '61f3fba4-862a-4989-90a3-32c91ec6db8e', value: 'DONE', label: 'Done', position: 2, color: 'green' },
        { id: '3a7cbc47-5fdc-4ce0-90f6-d619c97b266d', value: 'CANCELLED', label: 'Cancelled', position: 3, color: 'red' },
        { id: 'ffd76000-08ac-4bef-a758-c294d4fc9140', value: 'OVERDUE', label: 'Overdue', position: 4, color: 'orange' },
      ],
    },
    {
      universalIdentifier: TASK_PRIORITY_FIELD_UUID,
      type: FieldType.SELECT,
      name: 'priority',
      label: 'Priority',
      icon: 'IconFlag',
      defaultValue: "'MEDIUM'",
      options: [
        { id: 'a5843527-e021-4df6-bb30-b0c5b0b7cbf8', value: 'LOW', label: 'Low', position: 0, color: 'gray' },
        { id: '7f282a9f-539d-4cf8-baa4-0742c766a23f', value: 'MEDIUM', label: 'Medium', position: 1, color: 'sky' },
        { id: '9175eb85-2fa4-4e84-8f21-24677a86bd26', value: 'HIGH', label: 'High', position: 2, color: 'orange' },
        { id: 'f8efa44d-7c38-4fcd-9965-e50592198fec', value: 'URGENT', label: 'Urgent', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: TASK_DUE_DATE_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'dueDate',
      label: 'Due Date',
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    {
      universalIdentifier: TASK_REMINDER_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'reminderAt',
      label: 'Reminder At',
      icon: 'IconBell',
      isNullable: true,
    },
    {
      universalIdentifier: TASK_COMPLETED_AT_FIELD_UUID,
      type: FieldType.DATE_TIME,
      name: 'completedAt',
      label: 'Completed At',
      icon: 'IconCircleCheck',
      isNullable: true,
    },

    // ── System ────────────────────────────────────────────────────────────
    {
      universalIdentifier: TASK_POSITION_FIELD_UUID,
      type: FieldType.POSITION,
      name: 'position',
      label: 'Position',
      icon: 'IconList',
      isNullable: true,
    },
  ],
});
